<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="robot_arm" 
        params="mass=0.5 
                side=0.1 
                height=0.02 
                link_radius=0.02 
                link_length=0.3">
        <!-- property of the arm -->
        <xacro:property name="arm_base_mass" value="${mass}"/>
        <xacro:property name="arm_base_side" value="${side}"/>
        <xacro:property name="arm_base_height" value="${height}"/>
        <xacro:property name="arm_link_radius" value="${link_radius}"/>
        <xacro:property name="arm_link_length" value="${link_length}"/>

        <!-- robot arm links -->
        <link name="arm_base_link">
            <visual>
                <geometry>
                    <box size="${arm_base_side} ${arm_base_side} ${arm_base_height}"/>
                </geometry>
                <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
                <material name="orange"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${arm_base_side} ${arm_base_side} ${arm_base_height}"/>
                </geometry>
                <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
            </collision>
            <xacro:box_inertia m="${arm_base_mass}" x="${arm_base_side}" y="${arm_base_side}" z="${arm_base_height}"
                o_xyz="0 0 ${arm_base_height/2.0}" o_rpy="0 0 0"/>
        </link>

        <xacro:macro name="link" params="prefix color">
            <link name="${prefix}_link">
                <visual>
                    <geometry>
                        <cylinder radius="${arm_link_radius}" length="${arm_link_length}"/>
                    </geometry>
                <origin xyz="0 0 ${arm_link_length/2.0}" rpy="0 0 0"/>
                <material name="${color}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${arm_link_radius}" length="${arm_link_length}"/>
                </geometry>
                <origin xyz="0 0 ${arm_link_length/2.0}" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${arm_link_radius}" h="${arm_link_length}" 
                o_xyz="0 0 ${arm_link_length/2.0}" o_rpy="0 0 0"/>
            </link>
        </xacro:macro>

        <xacro:link prefix="forearm" color="yellow"/>
        <xacro:link prefix="hand" color="orange"/>

        <!-- robotic arm joints -->
        <joint name="base_forearm_joint" type="revolute">
            <parent link="arm_base_link"/>
            <child link="forearm_link"/>
            <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"/>
        </joint>

        <joint name="forearm_hand_joint" type="revolute">
            <parent link="forearm_link"/>
            <child link="hand_link"/>
            <origin xyz="0 0 ${arm_link_length}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"/>
        </joint>

        <!-- gazebo -->
        <gazebo reference="forearm_link">
            <mu1 value="0.3" />
            <mu2 value="0.3" />
        </gazebo>

        <gazebo reference="hand_link">
            <mu1 value="0.3" />
            <mu2 value="0.3" />
        </gazebo>

        <gazebo>
            <plugin filename="gz-sim-joint-state-publisher-system"
                name="gz::sim::systems::JointStatePublisher">
                <joint_name>base_forearm_joint</joint_name>
                <joint_name>forearm_hand_joint</joint_name>
            </plugin>
        </gazebo>

        <gazebo>
            <plugin filename="gz-sim-joint-position-controller-system"
                name="gz::sim::systems::JointPositionController">
                <joint_name>base_forearm_joint</joint_name>
                <initial_position>0.0</initial_position>
                <p_gain>5.0</p_gain>
                <i_gain>0.001</i_gain>
                <d_gain>1</d_gain>
            </plugin>
            <plugin filename="gz-sim-joint-position-controller-system"
                name="gz::sim::systems::JointPositionController">
                <joint_name>forearm_hand_joint</joint_name>
                <initial_position>0.0</initial_position>
                <p_gain>3.0</p_gain>
                <i_gain>0.001</i_gain>
                <d_gain>1</d_gain>
            </plugin>
        </gazebo>
    </xacro:macro>
</robot>